In [1]:
import numpy as np

In [2]:
two_dr_arr = np.arange(12).reshape(3,4)

In [3]:
two_dr_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
two_dr_arr[1][1]

5

In [5]:
two_dr_arr[1,1]

5

In [6]:
two_dr_arr[2,1]

9

In [7]:
two_dr_arr[:2, :2]

array([[0, 1],
       [4, 5]])

In [12]:
two_dr_arr[:3, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [15]:
arr = np.random.randint(1,20,10)

In [16]:
arr

array([11, 18, 15,  9, 17, 14,  7,  5, 16,  5])

In [17]:
arr_2 = arr[1:6]

In [18]:
print(arr)

[11 18 15  9 17 14  7  5 16  5]


In [19]:
print(arr_2)

[18 15  9 17 14]


In [20]:
arr = np.random.randint(0,20,10)

In [21]:
arr_2 = arr[3:]

In [22]:
print(arr)

[16  8 18  2 13 19  3 14  6  5]


In [23]:
print(arr_2)

[ 2 13 19  3 14  6  5]


In [24]:
arr = np.random.randint(0,11,12).reshape(4,3)

In [25]:
arr

array([[ 2, 10,  3],
       [ 8,  5,  1],
       [ 9,  5,  6],
       [ 4,  4, 10]])

In [27]:
arr_2 = arr[1:3]

In [28]:
print(arr_2)

[[8 5 1]
 [9 5 6]]


In [29]:
arr_3 = arr[:, 1:]

In [30]:
print(arr_3)

[[10  3]
 [ 5  1]
 [ 5  6]
 [ 4 10]]


In [31]:
arr = np.random.randint(0,9,24).reshape(4,6)

In [32]:
arr_2 = arr > 3

In [33]:
print(arr)

[[7 0 4 7 8 7]
 [0 4 1 5 3 6]
 [0 7 0 6 6 4]
 [8 6 1 3 7 4]]


In [34]:
print(arr_2)

[[ True False  True  True  True  True]
 [False  True False  True False  True]
 [False  True False  True  True  True]
 [ True  True False False  True  True]]


In [35]:
print(arr[arr_2])

[7 4 7 8 7 4 5 6 7 6 6 4 8 6 7 4]


In [36]:
arr = np.random.randint(3, 12, 12).reshape(4, 3)

In [37]:
arr

array([[11, 11,  4],
       [ 6,  5, 10],
       [ 6,  4,  7],
       [ 6,  4,  3]])

In [38]:
new_arr = arr[1:3, :2]

In [39]:
new_arr

array([[6, 5],
       [6, 4]])

In [40]:
new_arr_2 = arr[:, 1:]

In [41]:
new_arr_2

array([[11,  4],
       [ 5, 10],
       [ 4,  7],
       [ 4,  3]])

In [42]:
arr = np.random.randint(0,20,9).reshape(3,3)

In [43]:
arr

array([[ 0,  1,  9],
       [19,  1, 15],
       [16, 11, 16]])

In [44]:
arr_2 = arr[:2, 1:]

In [45]:
arr_2

array([[ 1,  9],
       [ 1, 15]])

In [46]:
arr_3 = arr[1:, :2]

In [47]:
arr_3

array([[19,  1],
       [16, 11]])