In [3]:
import numpy as np

In [5]:
int_arr = np.random.randint(0,10,10) 

In [6]:
int_arr

array([4, 5, 5, 2, 0, 9, 9, 2, 7, 1])

In [7]:
int_arr[0], int_arr[9]

(4, 1)

In [8]:
int_arr.argmax()

5

In [9]:
int_arr.argmin()

4

In [10]:
int_arr.max(), int_arr.min()

(9, 0)

In [16]:
int_arr[1:4]

array([5, 5, 2])

In [17]:
int_arr[1:4] = 10

In [18]:
int_arr

array([ 4, 10, 10, 10,  0,  9,  9,  2,  7,  1])

In [19]:
int_arr[1:4] = 9

In [20]:
int_arr

array([4, 9, 9, 9, 0, 9, 9, 2, 7, 1])

In [21]:
sec_arr = np.random.randint(0,20,15)

In [24]:
sec_arr

array([ 9, 19,  6,  1,  1,  1,  1,  3, 11,  1, 17, 17,  5,  7, 12])

In [23]:
sec_arr[4:7] = np.random.randint(3)

In [25]:
sec_arr

array([ 9, 19,  6,  1,  1,  1,  1,  3, 11,  1, 17, 17,  5,  7, 12])

In [26]:
sec_arr[4:7] = 2,3,4

In [27]:
sec_arr

array([ 9, 19,  6,  1,  2,  3,  4,  3, 11,  1, 17, 17,  5,  7, 12])

In [28]:
third_arr = sec_arr.copy()

In [29]:
third_arr

array([ 9, 19,  6,  1,  2,  3,  4,  3, 11,  1, 17, 17,  5,  7, 12])

In [30]:
third_arr > 15

array([False,  True, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [31]:
bool_arr = third_arr >15

In [32]:
bool_arr

array([False,  True, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [37]:
third_arr[bool_arr]

array([19, 17, 17])

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
arr = np.arange(8)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
arr > 4

array([False, False, False, False, False,  True,  True,  True])

In [42]:
arr_2 = arr > 4

In [43]:
arr_2

array([False, False, False, False, False,  True,  True,  True])

In [44]:
arr[arr_2]

array([5, 6, 7])

In [46]:
arr_2 = arr > 2

In [47]:
arr [arr_2]

array([3, 4, 5, 6, 7])