In [1]:
import numpy as np

In [4]:
arr = np.arange(1,11)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
arr = np.random.randint(1,20,10)

In [12]:
arr_2 = np.arange(2,12)

In [14]:
print(arr)

[ 1 19  8  4 13  5 16  5 14  6]


In [15]:
print(arr_2)

[ 2  3  4  5  6  7  8  9 10 11]


In [16]:
print(arr+arr_2)

[ 3 22 12  9 19 12 24 14 24 17]


In [17]:
arr = np.random.randint(0,9,7)

In [18]:
arr_2 = arr[:8]*3

In [19]:
print(arr)

[3 8 5 3 3 2 8]


In [20]:
print(arr_2)

[ 9 24 15  9  9  6 24]


In [22]:
arr = np.arange(7,27)

In [23]:
arr

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26])

In [29]:
print(np.sqrt(np.arange(7,27)))

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]
